#!/bin/sh

brew update
brew upgrade
brew prune
brew cleanup

# ça tapine
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap caskroom/cask
brew tap caskroom/versions
brew tap caskroom/fonts

# ouais lol
brew tap josegonzalez/homebrew-php

# la base, posey
brew install zsh
brew install git
brew install hub
brew install tig
brew install cloc
brew install node
brew install brew-cask
brew install wget
brew install vim
brew install heroku-toolbelt
brew install imagemagick # https://github.com/ggordan/GutterColor#icon-tinting-and-light-color-schemes
brew install the_silver_searcher
brew install ack
brew install ctags
brew install nvm
mkdir $HOME/.nvm
cp $(brew --prefix nvm)/nvm-exec ~/.nvm/
echo "export NVM_DIR=~/.nvm" >> ~/.zshrc
echo "source $(brew --prefix nvm)/nvm.sh" >> ~/.zshrc # need to do it in another session
nvm install iojs
nvm alias default iojs

# apps
brew cask install limechat
brew cask install dropbox
brew cask install spotify
brew cask install cloud
brew cask install hammerspoon
brew cask install iterm2
brew cask install grandperspective
brew cask install postico
brew cask install franz # slack, messenger, ...

# trop un pirateur tavu
brew cask install vlc

# required by some updates for brew
brew cask install xquartz

# web dev tavu
brew cask install atom
brew cask install firefox
brew cask install google-chrome
brew cask install virtualbox
brew cask install vagrant
brew cask install sequel-pro
brew cask install cyberduck

#fonts
brew cask install font-comic-neue
brew cask install font-fira-code
brew cask install font-roboto
brew cask install font-open-sans
brew cask install font-open-sans-condensed
brew cask install font-lato
brew cask install font-fantasque-sans-mono
