#!/bin/sh

brew update
brew upgrade

# ça tapine
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap phinze/cask
brew tap caskroom/versions
brew tap caskroom/fonts

# ouais lol
brew tap josegonzalez/homebrew-php

# la base, posey
brew install git
brew install node
brew install brew-cask
brew install wget
brew install vim

# apps
brew cask install limechat
brew cask install skype
brew cask install dropbox
brew cask install spotify
brew cask install cloud
brew cask install spectacle

# trop un pirateur tavu
brew cask install vlc
brew cask install subtitles

# required by some updates for brew
brew cask install xquartz

# web dev tavu
brew cask install sublime-text3
brew cask install firefox-nightly
brew cask install firefox
brew cask install google-chrome
brew cask install virtualbox
brew cask install vagrant
brew cask install sequel-pro

#fonts
brew cask install font-roboto
brew cask install font-open-sans
brew cask install font-open-sans-condensed
brew cask install font-lato
brew cask install font-fantasque-sans-mono
