#!/bin/sh

echo "donne moi les pleins pouvoirs, gros"
sudo -v

# install submodules recursively
git submodule update --remote --init --recursive

. cli/init.sh

source ./brewfile
echo "don't forget to install tweetbot, microsoft remote desktop"
source ./osx

if [ ! -f "$HOME/.gitconfig" ]; then
  cd ~
  ln -s ~/dotfiles/git/gitconfig .gitconfig
  ln -s ~/dotfiles/git/git_template .git_template
  cd ~/dotfiles
fi

if [ ! -e "$HOME/.github_token" ]; then
  echo "Saving a GitHub token"
  echo "Press a key to start the process"
  read -k
  echo "Please login into your GitHub account to get a token & paste it (or just type enter to bypass this step):"
  open "https://github.com/settings/applications"
  read GITHUB_TOKEN
  if [ "$GITHUB_TOKEN" != "" ]
  then
    echo $GITHUB_TOKEN > $HOME/.github_token
  fi
fi

if [ ! -f "$HOME/.ctags" ]; then
  cd ~
  ln -s ~/dotfiles/ctags/ctags .ctags
  cd ~/dotfiles
fi

if type vagrant >/dev/null; then
  vagrant plugin install vagrant-bindfs
  vagrant plugin install vagrant-vbguest
fi
