#!/bin/sh

echo "donne moi les pleins pouvoirs, gros"
sudo -v

if ! type "brew" > /dev/null; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if ! type "/usr/local/bin/zsh" > /dev/null; then
  brew install zsh
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/zsh
  echo "restart l'application de terminal pour finir l'install de zsh"
fi

zsh ./zshinstall

source ./brewfile
source ./osx

if [ ! -f "$HOME/.gitconfig" ]; then
  cd ~
  ln -s ~/dotfiles/git/gitconfig .gitconfig
  ln -s ~/dotfiles/git/git_template .git_template
  cd ~/dotfiles
fi

if [ ! -f "$HOME/.ctags" ]; then
  cd ~
  ln -s ~/dotfiles/ctags/ctags .ctags
  cd ~/dotfiles
fi
