set nocompatible 	  " we want vim not vi
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'kien/ctrlp.vim'
Plugin 'evidens/vim-twig'
Plugin 'mileszs/ack.vim'

call vundle#end()

" -- Display
set title
set number
set ruler
set wrap
set scrolloff=5		  " lines around cursor
set showcmd

" -- Recherche
set ignorecase
set smartcase
set incsearch
set hlsearch

" -- Beep
set visualbell
set noerrorbells

" Active le comportement 'habituel' de la touche retour en arriere
set backspace=indent,eol,start

set hidden

syntax enable
filetype on
filetype plugin indent on

set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set wildignore+=.git,.svn

" mapping
let mapleader = ","

map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber
:au FocusLost * :set number
:au FocusGained * :set relativenumber
function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc
nnoremap <Leader>n :call NumberToggle()<cr>

set backupdir=
set directory=
set nowritebackup
set noswapfile

" Esc -> ;;
:imap ;; <Esc>
:map ;; <Esc>

" CtrlP
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ -g ""'
nmap <Leader>oo :CtrlP<cr>

" Expand %% to dir of current file
cmap %% <C-R>=expand('%:h').'/'<cr>

"" Shared clipboard with the OS

set clipboard=unnamed

"" Spaces/Tabs

set expandtab "Use spaces instead of tabs
set shiftwidth=2
set tabstop=2

"" Indentation guides
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1

" ack
let g:ackprg="ag --nocolor --nogroup --column"
" Place un marqueur et cherche
nmap <leader>j mA:Ack<space>
" Place un marqueur et cherche le mot sous le curseur
nmap <leader>ja mA:Ack "<C-r>=expand("<cword>")<cr>"
nmap <leader>jA mA:Ack "<C-r>=expand("<cWORD>")<cr>"
