ulimit -n 1024

# Adding colors to man pages
man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias fuck='sudo $(history -p \!\!)'
# added by travis gem
[ -f /Users/sbalayn/.travis/travis.sh ] && source /Users/sbalayn/.travis/travis.sh

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=/Users/sbalayn/gocode

if [[ -f $HOME/.github_token ]]
then
  export GITHUB_TOKEN=$(cat $HOME/.github_token)
fi

export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"

alias git=hub

export PATH="$PATH:`yarn global bin`"

alias doma="docker-machine"
domae() { eval $(docker-machine env) }
alias domastart="docker-machine start && domae"

alias dockco="docker-compose"
alias dockcoupd="docker-compose up -d"
alias dockex="docker exec -it --user overblog docker_overblog_1 bash"
alias dockexroot="docker exec -it docker_overblog_1 bash"
dockexec() {
  current_path=`pwd`
  container_path=`grealpath --relative-to="$HOME/dev/overblog" "$current_path"`
  dockex -c "cd $container_path && eval $*"
} 
dockobcompinstall() {
  for project in $@;
    do dockex -c "cd overblog/projects/$project && composer install -n";
  done;
}
