#!/usr/bin/env zsh

# gpg encrypt
brew install gnupg2
# apm install atom-gpg
# vim +PlugInstall vim-gnupg
if grep -Fxq GPG_TTY ~/.zshrc ; then
  echo "export GPG_TTY=\`tty\`" >> ~/.zshrc
  source ~/.zshrc
fi
mkdir -p ~/.gnupg
chmod 700 ~/.gnupg
cp ~/dotfiles/overblog/gpg.conf ~/.gnupg/gpg.conf

echo 'for the key creation: enter, enter, "1y", "y", "Sebastien Balayn", "sebastien@overblog.com", "Sebastien.Balayn", "O", a passphrase,
gpg --full-gen-key
gpg --armor --export sebastien@overblog.com > ~/dev/overblog/overblog/keys/sebastien@overblog.com.public.key
gpg --import ~/dev/overblog/overblog/keys/*.public.key
